ex02-module-class
hubertkozik/highcharts-modules pull request #2
Opened 2023-03-01 14:17 UTC by hubertkozik

Second exercise.

2023-03-07 10:41 UTC, pawelfus requested changes

2023-03-07 10:41 UTC, pawelfus commented on exercises/02-module-class/color-generator-2.0.mjs
> +    colors = ['red', 'green', 'blue'];
This field should be [private](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields)

From [exercise description](https://github.com/hubertkozik/highcharts-modules/tree/main/exercises/02-module-class):
> Implement a [Class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) with:
> 
> a) Public methods:
> 
> `get(n?: number): Array<string>;`
> `reset(): void;`
**> b) Private properties and methods:**
> 
> `colors: Array<string>`
> any other properties and methods you need

2023-03-07 10:41 UTC, pawelfus commented on exercises/02-module-class/color-generator-2.0.mjs
> +    get(n) {
Not a bug, but during your code reviews in this classroom, if possible please promote [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) usage

I can't complain about your solution, it is smart :D But junior devs tend to solve it in different ways, for example: 
```ts
get(n) {
  const count = n || 1;
}
```
Or:
```ts
get(n) {
  if (!n) {

  }  else ...
}
```

Which could be simpler with default params

2023-03-07 10:41 UTC, pawelfus commented on exercises/02-module-class/color-generator-2.0.mjs
> +    i = 0;
Not a bug per se, but a bit more descriptive name would be nice 😅 For example `counter` or `index`.

2023-04-11 07:51 UTC, hubertkozik commented on exercises/02-module-class/color-generator-2.0.mjs
> +    get(n) {
I have changed this part of the code to use default parameters, but in my opinion, the code looked better in my first solution 😀 But I understand, that default parameters should be promoted and I will remember about it, when doing some future code reviews 🙂

2023-12-12 08:51 UTC, closed without merging